### ISSUE TITLE
Engines built on LÖVE?

### ISSUE THREAD

**Issue by andrewmcwatters** [JanWerder/awesome-love2d#16]
I don't know if this has a place here, since it's probably not appropriate for the list, but thought I might ask.

The folks from @Planimeter and I have been working on [Grid](http://www.planimeter.org/grid/) for a while and was wondering if it would be appropriate to add to an _Engines powered by LÖVE_ category or something of the sort.

There's a small handful of us in the engine development community that have built full-blown engines on LÖVE's framework and thought it would be a nice addition to the list.

If that's acceptable, I'll submit a PR, but wanted to check beforehand.

**Comment by JanWerder** [comment]
I think the idea of showing Engines built on Löve is great. I actually had a category for that in my initial draft. But since the only nearly finished Löve Engine I could find was by @adonaac I removed the category.

So overall I would love to have them in the list, but the documentation has to on par with the other libraries. That doesn't seem to be the case with Grid though. The [Features](http://www.planimeter.org/grid/features/Pathfinding), [Tutorials](http://www.planimeter.org/grid/tutorials/Home) & [API](http://www.planimeter.org/grid/api/gui.dropdownlistitemgroup) are missing descriptions and examples. I'm sorry but in this state I won't add it to the list ([happend before](https://github.com/JanWerder/awesome-love2d/pull/11) and is noted in the [contribution notes](https://github.com/JanWerder/awesome-love2d/blob/master/CONTRIBUTING.md))
